# pytest.ini file to configure pytest settings and markers
# Best left in root project folder: pytest looks for pytest.ini starting from where you run the command
[pytest]
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
